# Generated by Django 2.2.16 on 2023-03-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
