# Generated by Django 2.2.16 on 2023-03-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20230328_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
